export const pools = [
  {
    name: "CPYT",
    status: "RAISING",
    duration: 9,
    APY: 12,
    issuance_date: new Date("06-30-2024".replace(/-/g, "/")).toISOString(),
    first_repayment: new Date("03-31-2025".replace(/-/g, "/")).toISOString(),
    last_repayment: new Date("09-30-2025".replace(/-/g, "/")).toISOString(),
    raised: 25000,
    goal: 50000,
    payback: "Quarterly",
    id: "1",
  },
  {
    name: "CPYT",
    status: "EARNING",
    duration: 9,
    APY: 12,
    issuance_date: new Date("01-31-2024".replace(/-/g, "/")).toISOString(),
    first_repayment: new Date("07-30-2024".replace(/-/g, "/")).toISOString(),
    last_repayment: new Date("03-31-2025".replace(/-/g, "/")).toISOString(),
    raised: 25000,
    goal: 100000,
    payback: "Quarterly",
    id: "2",
  },
  {
    name: "CPYT",
    status: "COMPLETED",
    duration: 9,
    APY: 12,
    issuance_date: new Date("06-30-2023".replace(/-/g, "/")).toISOString(),
    first_repayment: new Date("03-31-2024".replace(/-/g, "/")).toISOString(),
    last_repayment: new Date("09-30-2024".replace(/-/g, "/")).toISOString(),
    raised: 100000,
    goal: 100000,
    payback: "Quarterly",
    id: "3",
  },
];
