import { COLLATERAL_ASSET_CODE } from "@/constants";

export const currencies = [
  {
    currency: "TZS",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762632/assets/Flag_of_Tanzania_glo5cu.svg",
    symbol: "TSh",
    minTransfer: 5999,
    maxTransfer: 10000000,
    currencyType: "FIAT",
  },
  {
    currency: "USD",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762630/assets/1200px-Flag_of_the_United_States.svg_bicuij.png",
    symbol: "$",
    minTransfer: 9,
    maxTransfer: 10000,
    currencyType: "FIAT",
  },
  {
    currency: "KES",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762632/assets/Flag_of_Kenya_bjxu6o.svg",
    symbol: "KSh",
    minTransfer: 49,
    maxTransfer: 10000000,
    currencyType: "FIAT",
  },
  {
    currency: "RWF",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762633/assets/Flag_of_Rwanda_yzehtb.svg",
    symbol: "R₣",
    minTransfer: 1999,
    maxTransfer: 2000000,
    currencyType: "FIAT",
  },
  {
    currency: "GBP",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762630/assets/1200px-Flag_of_the_United_Kingdom.svg_fnhe2c.png",
    symbol: "£",
    minTransfer: 9,
    maxTransfer: 10000,
    currencyType: "FIAT",
  },
  {
    currency: "EUR",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762632/assets/Flag_of_Europe_pbszhq.svg",
    symbol: "€",
    minTransfer: 9,
    maxTransfer: 10000,
    currencyType: "FIAT",
  },
  {
    currency: "XLM",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675763976/assets/Logo_Large_Black_zt8hms.svg",
    symbol: "XLM",
    minTransfer: 0,
    maxTransfer: 0,
    currencyType: "CRYPTO",
  },
  {
    currency: "BTC",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762631/assets/BTC_Logo_lyqqkm.svg",
    symbol: "BTC",
    minTransfer: 0,
    maxTransfer: 0,
    currencyType: "CRYPTO",
  },
  {
    currency: "ETH",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762632/assets/ethereum-og-logo_d5krlk.png",
    symbol: "ETH",
    minTransfer: 0,
    maxTransfer: 0,
    currencyType: "CRYPTO",
  },
  {
    currency: "USDT",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675762630/assets/345-3451812_tether-usdt-icon-usdt-tether-logo-clipart_lewbwy.jpg",
    symbol: "USDT",
    minTransfer: 0,
    maxTransfer: 0,
    currencyType: "CRYPTO",
  },
  {
    currency: "USDC",
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1675763995/assets/usdc_qx0rfh.svg",
    symbol: "USDC",
    minTransfer: 0,
    maxTransfer: 0,
    currencyType: "CRYPTO",
  },
  {
    currency: COLLATERAL_ASSET_CODE,
    icon: "https://res.cloudinary.com/dnhpcrm8k/image/upload/v1717765302/assets/debt-fund-icon_izr8j5.svg",
    symbol: COLLATERAL_ASSET_CODE,
    minTransfer: 0,
    maxTransfer: 0,
    currencyType: "CRYPTO",
  },
];
